// <auto-generated />
#nullable enable
#pragma warning disable
using global::System;
using global::System.Linq;
using global::System.Collections.Generic;
using global::System.Threading.Tasks;
using global::System.Diagnostics;
using global::System.Runtime.CompilerServices;
using global::Imposter.Abstractions;
using global::System.Collections.Concurrent;
using global::Imposter.Tests.Features.PropertyImpersonation;

namespace Imposter.Tests.Features.PropertyImpersonation
{
    [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
    public sealed class IPropertySetupSutImposter : global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut>
    {
        private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
        private ImposterTargetInstance _imposterInstance;
        global::Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut global::Imposter.Abstractions.IHaveImposterInstance<global::Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut>.Instance()
        {
            return _imposterInstance;
        }

        public IAgePropertyBuilder Age => _AgePropertyBuilderField;

        private readonly AgePropertyBuilder _AgePropertyBuilderField;
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertyGetterOutcomeBuilder
        {
            IAgePropertyGetterContinuationBuilder Returns(int value);
            IAgePropertyGetterContinuationBuilder Returns(global::System.Func<int> valueGenerator);
            IAgePropertyGetterContinuationBuilder Throws(global::System.Exception exception);
            IAgePropertyGetterContinuationBuilder Throws<TException>()
                where TException : Exception, new();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertyGetterCallbackBuilder
        {
            IAgePropertyGetterContinuationBuilder Callback(global::System.Action callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertyGetterContinuationBuilder : IAgePropertyGetterCallbackBuilder
        {
            IAgePropertyGetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertyGetterVerifier
        {
            void HaveBeenCalled(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertyGetterFluentBuilder : IAgePropertyGetterOutcomeBuilder, IAgePropertyGetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertyGetterBuilder : global::Imposter.Abstractions.IHaveInvocationVerifier<IAgePropertyGetterVerifier>, IAgePropertyGetterOutcomeBuilder, IAgePropertyGetterCallbackBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertySetterCallbackBuilder
        {
            IAgePropertySetterContinuationBuilder Callback(global::System.Action<int> callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertySetterContinuationBuilder : IAgePropertySetterCallbackBuilder
        {
            IAgePropertySetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertySetterFluentBuilder : IAgePropertySetterCallbackBuilder, IAgePropertySetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertySetterVerifier
        {
            void HaveBeenCalled(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertySetterBuilder : global::Imposter.Abstractions.IHaveInvocationVerifier<IAgePropertySetterVerifier>, IAgePropertySetterCallbackBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface IAgePropertyBuilder
        {
            IAgePropertyGetterBuilder Getter();
            IAgePropertySetterBuilder Setter(global::Imposter.Abstractions.Arg<int> criteria);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class AgePropertyBuilder : IAgePropertyBuilder
        {
            private readonly DefaultPropertyBehaviour _defaultPropertyBehaviour;
            private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
            internal SetterImposter _setterImposter;
            internal GetterImposterBuilder _getterImposterBuilder;
            internal AgePropertyBuilder(global::Imposter.Abstractions.ImposterMode invocationBehavior)
            {
                _defaultPropertyBehaviour = new DefaultPropertyBehaviour();
                _invocationBehavior = invocationBehavior;
                _getterImposterBuilder = new GetterImposterBuilder(_defaultPropertyBehaviour, _invocationBehavior, "Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut.Age");
                _setterImposter = new SetterImposter(_defaultPropertyBehaviour, _invocationBehavior, "Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut.Age");
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class DefaultPropertyBehaviour
            {
                internal volatile bool IsOn = true;
                internal volatile bool HasValueSet = false;
                internal int BackingField = default !;
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class GetterImposterBuilder : global::Imposter.Abstractions.HaveInvocationVerifier<IAgePropertyGetterVerifier>, IAgePropertyGetterBuilder, IAgePropertyGetterFluentBuilder
            {
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<global::System.Func<int>?, int>> _returnValues = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<global::System.Func<int>?, int>>();
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action>();
                private volatile global::System.Func<global::System.Func<int>?, int> _lastReturnValue = _ => default !;
                private int _invocationCount;
                private readonly DefaultPropertyBehaviour _defaultPropertyBehaviour;
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredReturn;
                internal GetterImposterBuilder(DefaultPropertyBehaviour _defaultPropertyBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultPropertyBehaviour = _defaultPropertyBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                    base.InitializeInvocationVerifier(new HaveBeenCalledProxy(this));
                }

                private void AddReturnValue(global::System.Func<global::System.Func<int>?, int> valueGenerator)
                {
                    _defaultPropertyBehaviour.IsOn = false;
                    _returnValues.Enqueue(valueGenerator);
                    _hasConfiguredReturn = true;
                }

                IAgePropertyGetterContinuationBuilder IAgePropertyGetterOutcomeBuilder.Returns(int value)
                {
                    AddReturnValue((_) => value);
                    return this;
                }

                IAgePropertyGetterContinuationBuilder IAgePropertyGetterOutcomeBuilder.Returns(global::System.Func<int> valueGenerator)
                {
                    AddReturnValue((_) => valueGenerator());
                    return this;
                }

                IAgePropertyGetterContinuationBuilder IAgePropertyGetterOutcomeBuilder.Throws(global::System.Exception exception)
                {
                    AddReturnValue((_) => throw exception);
                    return this;
                }

                IAgePropertyGetterContinuationBuilder IAgePropertyGetterOutcomeBuilder.Throws<TException>()
                {
                    AddReturnValue((_) => throw new TException());
                    return this;
                }

                IAgePropertyGetterContinuationBuilder IAgePropertyGetterCallbackBuilder.Callback(global::System.Action callback)
                {
                    _callbacks.Enqueue(callback);
                    return this;
                }

                void HaveBeenCalled(global::Imposter.Abstractions.Count count)
                {
                    if (!count.Matches(_invocationCount))
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, _invocationCount);
                }

                class HaveBeenCalledProxy : IAgePropertyGetterVerifier
                {
                    GetterImposterBuilder _owner;
                    internal HaveBeenCalledProxy(GetterImposterBuilder owner)
                    {
                        _owner = owner;
                    }

                    void IAgePropertyGetterVerifier.HaveBeenCalled(global::Imposter.Abstractions.Count count) => _owner.HaveBeenCalled(count);
                }

                IAgePropertyGetterFluentBuilder IAgePropertyGetterContinuationBuilder.Then()
                {
                    return this;
                }

                internal int Get(global::System.Func<int>? baseImplementation = null)
                {
                    EnsureGetterConfigured();
                    global::System.Threading.Interlocked.Increment(ref _invocationCount);
                    foreach (var getterCallback in _callbacks)
                    {
                        getterCallback();
                    }

                    if (_defaultPropertyBehaviour.IsOn)
                    {
                        if (((_invocationCount == 1) && (baseImplementation != null)) && !_defaultPropertyBehaviour.HasValueSet)
                        {
                            _defaultPropertyBehaviour.BackingField = baseImplementation();
                        }

                        return _defaultPropertyBehaviour.BackingField;
                    }

                    var nextReturnValue = _lastReturnValue;
                    if (_returnValues.TryDequeue(out var returnValue) && (returnValue != null))
                    {
                        nextReturnValue = returnValue;
                        _lastReturnValue = returnValue;
                    }

                    return nextReturnValue(baseImplementation);
                }

                private void EnsureGetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !_hasConfiguredReturn)
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                }
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class SetterImposter
            {
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Tuple<global::Imposter.Abstractions.Arg<int>, global::System.Action<int>>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Tuple<global::Imposter.Abstractions.Arg<int>, global::System.Action<int>>>();
                private readonly global::System.Collections.Concurrent.ConcurrentStack<int> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentStack<int>();
                private readonly DefaultPropertyBehaviour _defaultPropertyBehaviour;
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredSetter;
                internal SetterImposter(DefaultPropertyBehaviour _defaultPropertyBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultPropertyBehaviour = _defaultPropertyBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                internal void Callback(global::Imposter.Abstractions.Arg<int> criteria, global::System.Action<int> callback)
                {
                    _callbacks.Enqueue(new global::System.Tuple<global::Imposter.Abstractions.Arg<int>, global::System.Action<int>>(criteria, callback));
                }

                void HaveBeenCalled(global::Imposter.Abstractions.Arg<int> criteria, global::Imposter.Abstractions.Count count)
                {
                    var invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        var performedInvocations = new global::System.Collections.Generic.List<string>();
                        foreach (var value in _invocationHistory)
                        {
                            performedInvocations.Add("set " + _propertyDisplayName + " = " + FormatValue(value));
                        }

                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount, string.Join(Environment.NewLine, performedInvocations));
                    }
                }

                internal void Set(int value, global::System.Action<int>? baseImplementation = null)
                {
                    EnsureSetterConfigured();
                    _invocationHistory.Push(value);
                    foreach (var(criteria, setterCallback)in _callbacks)
                    {
                        if (criteria.Matches(value))
                            setterCallback(value);
                    }

                    if (_defaultPropertyBehaviour.IsOn)
                    {
                        _defaultPropertyBehaviour.BackingField = value;
                        _defaultPropertyBehaviour.HasValueSet = true;
                    }
                }

                private void EnsureSetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !_hasConfiguredSetter)
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (setter)");
                }

                internal void MarkConfigured()
                {
                    _hasConfiguredSetter = true;
                }

                private static string FormatValue(object? value)
                {
                    return "<" + (value?.ToString() ?? "null") + ">";
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : global::Imposter.Abstractions.HaveInvocationVerifier<IAgePropertySetterVerifier>, IAgePropertySetterBuilder, IAgePropertySetterFluentBuilder
                {
                    private readonly SetterImposter _setterImposter;
                    private readonly global::Imposter.Abstractions.Arg<int> _criteria;
                    internal Builder(SetterImposter _setterImposter, global::Imposter.Abstractions.Arg<int> _criteria)
                    {
                        this._setterImposter = _setterImposter;
                        this._criteria = _criteria;
                        base.InitializeInvocationVerifier(new HaveBeenCalledProxy(this));
                    }

                    IAgePropertySetterContinuationBuilder IAgePropertySetterCallbackBuilder.Callback(global::System.Action<int> callback)
                    {
                        _setterImposter.Callback(_criteria, callback);
                        return this;
                    }

                    void HaveBeenCalled(global::Imposter.Abstractions.Count count)
                    {
                        _setterImposter.HaveBeenCalled(_criteria, count);
                    }

                    class HaveBeenCalledProxy : IAgePropertySetterVerifier
                    {
                        SetterImposter.Builder _owner;
                        internal HaveBeenCalledProxy(SetterImposter.Builder owner)
                        {
                            _owner = owner;
                        }

                        void IAgePropertySetterVerifier.HaveBeenCalled(global::Imposter.Abstractions.Count count) => _owner.HaveBeenCalled(count);
                    }

                    IAgePropertySetterFluentBuilder IAgePropertySetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }
            }

            IAgePropertyGetterBuilder IAgePropertyBuilder.Getter()
            {
                return _getterImposterBuilder;
            }

            IAgePropertySetterBuilder IAgePropertyBuilder.Setter(global::Imposter.Abstractions.Arg<int> criteria)
            {
                _setterImposter.MarkConfigured();
                return new SetterImposter.Builder(_setterImposter, criteria);
            }
        }

        public ILastNamePropertyBuilder LastName => _LastNamePropertyBuilderField;

        private readonly LastNamePropertyBuilder _LastNamePropertyBuilderField;
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface ILastNamePropertySetterCallbackBuilder
        {
            ILastNamePropertySetterContinuationBuilder Callback(global::System.Action<int> callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface ILastNamePropertySetterContinuationBuilder : ILastNamePropertySetterCallbackBuilder
        {
            ILastNamePropertySetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface ILastNamePropertySetterFluentBuilder : ILastNamePropertySetterCallbackBuilder, ILastNamePropertySetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface ILastNamePropertySetterVerifier
        {
            void HaveBeenCalled(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface ILastNamePropertySetterBuilder : global::Imposter.Abstractions.IHaveInvocationVerifier<ILastNamePropertySetterVerifier>, ILastNamePropertySetterCallbackBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface ILastNamePropertyBuilder
        {
            ILastNamePropertySetterBuilder Setter(global::Imposter.Abstractions.Arg<int> criteria);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class LastNamePropertyBuilder : ILastNamePropertyBuilder
        {
            private readonly DefaultPropertyBehaviour _defaultPropertyBehaviour;
            private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
            internal SetterImposter _setterImposter;
            internal LastNamePropertyBuilder(global::Imposter.Abstractions.ImposterMode invocationBehavior)
            {
                _defaultPropertyBehaviour = new DefaultPropertyBehaviour();
                _invocationBehavior = invocationBehavior;
                _setterImposter = new SetterImposter(_defaultPropertyBehaviour, _invocationBehavior, "Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut.LastName");
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class DefaultPropertyBehaviour
            {
                internal volatile bool IsOn = true;
                internal volatile bool HasValueSet = false;
                internal int BackingField = default !;
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class SetterImposter
            {
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Tuple<global::Imposter.Abstractions.Arg<int>, global::System.Action<int>>> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Tuple<global::Imposter.Abstractions.Arg<int>, global::System.Action<int>>>();
                private readonly global::System.Collections.Concurrent.ConcurrentStack<int> _invocationHistory = new global::System.Collections.Concurrent.ConcurrentStack<int>();
                private readonly DefaultPropertyBehaviour _defaultPropertyBehaviour;
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredSetter;
                internal SetterImposter(DefaultPropertyBehaviour _defaultPropertyBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultPropertyBehaviour = _defaultPropertyBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                }

                internal void Callback(global::Imposter.Abstractions.Arg<int> criteria, global::System.Action<int> callback)
                {
                    _callbacks.Enqueue(new global::System.Tuple<global::Imposter.Abstractions.Arg<int>, global::System.Action<int>>(criteria, callback));
                }

                void HaveBeenCalled(global::Imposter.Abstractions.Arg<int> criteria, global::Imposter.Abstractions.Count count)
                {
                    var invocationCount = _invocationHistory.Count(criteria.Matches);
                    if (!count.Matches(invocationCount))
                    {
                        var performedInvocations = new global::System.Collections.Generic.List<string>();
                        foreach (var value in _invocationHistory)
                        {
                            performedInvocations.Add("set " + _propertyDisplayName + " = " + FormatValue(value));
                        }

                        throw new global::Imposter.Abstractions.VerificationFailedException(count, invocationCount, string.Join(Environment.NewLine, performedInvocations));
                    }
                }

                internal void Set(int value, global::System.Action<int>? baseImplementation = null)
                {
                    EnsureSetterConfigured();
                    _invocationHistory.Push(value);
                    foreach (var(criteria, setterCallback)in _callbacks)
                    {
                        if (criteria.Matches(value))
                            setterCallback(value);
                    }

                    if (_defaultPropertyBehaviour.IsOn)
                    {
                        _defaultPropertyBehaviour.BackingField = value;
                        _defaultPropertyBehaviour.HasValueSet = true;
                    }
                }

                private void EnsureSetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !_hasConfiguredSetter)
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (setter)");
                }

                internal void MarkConfigured()
                {
                    _hasConfiguredSetter = true;
                }

                private static string FormatValue(object? value)
                {
                    return "<" + (value?.ToString() ?? "null") + ">";
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
                internal class Builder : global::Imposter.Abstractions.HaveInvocationVerifier<ILastNamePropertySetterVerifier>, ILastNamePropertySetterBuilder, ILastNamePropertySetterFluentBuilder
                {
                    private readonly SetterImposter _setterImposter;
                    private readonly global::Imposter.Abstractions.Arg<int> _criteria;
                    internal Builder(SetterImposter _setterImposter, global::Imposter.Abstractions.Arg<int> _criteria)
                    {
                        this._setterImposter = _setterImposter;
                        this._criteria = _criteria;
                        base.InitializeInvocationVerifier(new HaveBeenCalledProxy(this));
                    }

                    ILastNamePropertySetterContinuationBuilder ILastNamePropertySetterCallbackBuilder.Callback(global::System.Action<int> callback)
                    {
                        _setterImposter.Callback(_criteria, callback);
                        return this;
                    }

                    void HaveBeenCalled(global::Imposter.Abstractions.Count count)
                    {
                        _setterImposter.HaveBeenCalled(_criteria, count);
                    }

                    class HaveBeenCalledProxy : ILastNamePropertySetterVerifier
                    {
                        SetterImposter.Builder _owner;
                        internal HaveBeenCalledProxy(SetterImposter.Builder owner)
                        {
                            _owner = owner;
                        }

                        void ILastNamePropertySetterVerifier.HaveBeenCalled(global::Imposter.Abstractions.Count count) => _owner.HaveBeenCalled(count);
                    }

                    ILastNamePropertySetterFluentBuilder ILastNamePropertySetterContinuationBuilder.Then()
                    {
                        return this;
                    }
                }
            }

            ILastNamePropertySetterBuilder ILastNamePropertyBuilder.Setter(global::Imposter.Abstractions.Arg<int> criteria)
            {
                _setterImposter.MarkConfigured();
                return new SetterImposter.Builder(_setterImposter, criteria);
            }
        }

        public INamePropertyBuilder Name => _NamePropertyBuilderField;

        private readonly NamePropertyBuilder _NamePropertyBuilderField;
        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface INamePropertyGetterOutcomeBuilder
        {
            INamePropertyGetterContinuationBuilder Returns(int value);
            INamePropertyGetterContinuationBuilder Returns(global::System.Func<int> valueGenerator);
            INamePropertyGetterContinuationBuilder Throws(global::System.Exception exception);
            INamePropertyGetterContinuationBuilder Throws<TException>()
                where TException : Exception, new();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface INamePropertyGetterCallbackBuilder
        {
            INamePropertyGetterContinuationBuilder Callback(global::System.Action callback);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface INamePropertyGetterContinuationBuilder : INamePropertyGetterCallbackBuilder
        {
            INamePropertyGetterFluentBuilder Then();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface INamePropertyGetterVerifier
        {
            void HaveBeenCalled(global::Imposter.Abstractions.Count count);
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface INamePropertyGetterFluentBuilder : INamePropertyGetterOutcomeBuilder, INamePropertyGetterContinuationBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface INamePropertyGetterBuilder : global::Imposter.Abstractions.IHaveInvocationVerifier<INamePropertyGetterVerifier>, INamePropertyGetterOutcomeBuilder, INamePropertyGetterCallbackBuilder
        {
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        public interface INamePropertyBuilder
        {
            INamePropertyGetterBuilder Getter();
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        internal class NamePropertyBuilder : INamePropertyBuilder
        {
            private readonly DefaultPropertyBehaviour _defaultPropertyBehaviour;
            private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
            internal GetterImposterBuilder _getterImposterBuilder;
            internal NamePropertyBuilder(global::Imposter.Abstractions.ImposterMode invocationBehavior)
            {
                _defaultPropertyBehaviour = new DefaultPropertyBehaviour();
                _invocationBehavior = invocationBehavior;
                _getterImposterBuilder = new GetterImposterBuilder(_defaultPropertyBehaviour, _invocationBehavior, "Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut.Name");
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class DefaultPropertyBehaviour
            {
                internal volatile bool IsOn = true;
                internal volatile bool HasValueSet = false;
                internal int BackingField = default !;
            }

            [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
            internal class GetterImposterBuilder : global::Imposter.Abstractions.HaveInvocationVerifier<INamePropertyGetterVerifier>, INamePropertyGetterBuilder, INamePropertyGetterFluentBuilder
            {
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<global::System.Func<int>?, int>> _returnValues = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Func<global::System.Func<int>?, int>>();
                private readonly global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action> _callbacks = new global::System.Collections.Concurrent.ConcurrentQueue<global::System.Action>();
                private volatile global::System.Func<global::System.Func<int>?, int> _lastReturnValue = _ => default !;
                private int _invocationCount;
                private readonly DefaultPropertyBehaviour _defaultPropertyBehaviour;
                private readonly global::Imposter.Abstractions.ImposterMode _invocationBehavior;
                private readonly string _propertyDisplayName;
                private bool _hasConfiguredReturn;
                internal GetterImposterBuilder(DefaultPropertyBehaviour _defaultPropertyBehaviour, global::Imposter.Abstractions.ImposterMode invocationBehavior, string propertyDisplayName)
                {
                    this._defaultPropertyBehaviour = _defaultPropertyBehaviour;
                    this._invocationBehavior = invocationBehavior;
                    this._propertyDisplayName = propertyDisplayName;
                    base.InitializeInvocationVerifier(new HaveBeenCalledProxy(this));
                }

                private void AddReturnValue(global::System.Func<global::System.Func<int>?, int> valueGenerator)
                {
                    _defaultPropertyBehaviour.IsOn = false;
                    _returnValues.Enqueue(valueGenerator);
                    _hasConfiguredReturn = true;
                }

                INamePropertyGetterContinuationBuilder INamePropertyGetterOutcomeBuilder.Returns(int value)
                {
                    AddReturnValue((_) => value);
                    return this;
                }

                INamePropertyGetterContinuationBuilder INamePropertyGetterOutcomeBuilder.Returns(global::System.Func<int> valueGenerator)
                {
                    AddReturnValue((_) => valueGenerator());
                    return this;
                }

                INamePropertyGetterContinuationBuilder INamePropertyGetterOutcomeBuilder.Throws(global::System.Exception exception)
                {
                    AddReturnValue((_) => throw exception);
                    return this;
                }

                INamePropertyGetterContinuationBuilder INamePropertyGetterOutcomeBuilder.Throws<TException>()
                {
                    AddReturnValue((_) => throw new TException());
                    return this;
                }

                INamePropertyGetterContinuationBuilder INamePropertyGetterCallbackBuilder.Callback(global::System.Action callback)
                {
                    _callbacks.Enqueue(callback);
                    return this;
                }

                void HaveBeenCalled(global::Imposter.Abstractions.Count count)
                {
                    if (!count.Matches(_invocationCount))
                        throw new global::Imposter.Abstractions.VerificationFailedException(count, _invocationCount);
                }

                class HaveBeenCalledProxy : INamePropertyGetterVerifier
                {
                    GetterImposterBuilder _owner;
                    internal HaveBeenCalledProxy(GetterImposterBuilder owner)
                    {
                        _owner = owner;
                    }

                    void INamePropertyGetterVerifier.HaveBeenCalled(global::Imposter.Abstractions.Count count) => _owner.HaveBeenCalled(count);
                }

                INamePropertyGetterFluentBuilder INamePropertyGetterContinuationBuilder.Then()
                {
                    return this;
                }

                internal int Get(global::System.Func<int>? baseImplementation = null)
                {
                    EnsureGetterConfigured();
                    global::System.Threading.Interlocked.Increment(ref _invocationCount);
                    foreach (var getterCallback in _callbacks)
                    {
                        getterCallback();
                    }

                    if (_defaultPropertyBehaviour.IsOn)
                    {
                        if (((_invocationCount == 1) && (baseImplementation != null)) && !_defaultPropertyBehaviour.HasValueSet)
                        {
                            _defaultPropertyBehaviour.BackingField = baseImplementation();
                        }

                        return _defaultPropertyBehaviour.BackingField;
                    }

                    var nextReturnValue = _lastReturnValue;
                    if (_returnValues.TryDequeue(out var returnValue) && (returnValue != null))
                    {
                        nextReturnValue = returnValue;
                        _lastReturnValue = returnValue;
                    }

                    return nextReturnValue(baseImplementation);
                }

                private void EnsureGetterConfigured()
                {
                    if ((_invocationBehavior == global::Imposter.Abstractions.ImposterMode.Explicit) && !_hasConfiguredReturn)
                        throw new global::Imposter.Abstractions.MissingImposterException(_propertyDisplayName + " (getter)");
                }
            }

            INamePropertyGetterBuilder INamePropertyBuilder.Getter()
            {
                return _getterImposterBuilder;
            }
        }

        public IPropertySetupSutImposter(global::Imposter.Abstractions.ImposterMode invocationBehavior = global::Imposter.Abstractions.ImposterMode.Implicit)
        {
            this._AgePropertyBuilderField = new AgePropertyBuilder(invocationBehavior);
            this._LastNamePropertyBuilderField = new LastNamePropertyBuilder(invocationBehavior);
            this._NamePropertyBuilderField = new NamePropertyBuilder(invocationBehavior);
            this._imposterInstance = new ImposterTargetInstance(this);
            this._invocationBehavior = invocationBehavior;
        }

        [global::System.CodeDom.Compiler.GeneratedCode("Imposter.CodeGenerator", "0.1.0.0")]
        class ImposterTargetInstance : global::Imposter.Tests.Features.PropertyImpersonation.IPropertySetupSut
        {
            private readonly IPropertySetupSutImposter _imposter;
            public ImposterTargetInstance(IPropertySetupSutImposter _imposter)
            {
                this._imposter = _imposter;
            }

            public int Age
            {
                get
                {
                    return _imposter._AgePropertyBuilderField._getterImposterBuilder.Get();
                }

                set
                {
                    _imposter._AgePropertyBuilderField._setterImposter.Set(value);
                }
            }

            public int LastName
            {
                set
                {
                    _imposter._LastNamePropertyBuilderField._setterImposter.Set(value);
                }
            }

            public int Name
            {
                get
                {
                    return _imposter._NamePropertyBuilderField._getterImposterBuilder.Get();
                }
            }
        }
    }
}
#nullable restore
#pragma warning restore
